### Consultando todos los tipos
GET http://localhost:3000/tipos

### Consultando un tipo
GET http://localhost:3000/tipos/8

### Insertando un tipo
POST http://localhost:3000/tipos
Content-Type: application/json

 {
    "tipo": "Alcancias2"
  }

### Actualizando un tipo
PUT http://localhost:3000/tipos/12
Content-Type: application/json

  {
    "id_tipo": 12,
    "tipo": "Saleros"
  }

### Eliminando un tipo
DELETE http://localhost:3000/tipos/12

### Consultando todos los usuarios
GET http://localhost:3000/usuarios

### Consultando un usuario
GET http://localhost:3000/usuarios/5

### Insertando un usuario
POST http://localhost:3000/usuarios
Content-Type: application/json

  {
    "nom_usuario": "Yo mero",
    "clave": "hola123",
    "correo": "apolinartrejo@utng.edu.mx"
  }

### Actualizando un tipo
PUT http://localhost:3000/usuarios/5
Content-Type: application/json

  {
    "id_usuario": 5,
    "nom_usuario": "Yo mero",
    "clave": "abracadabra",
    "correo": "apolinartrejo@utng.edu.mx"
  }

### Eliminando un usuario
DELETE http://localhost:3000/usuarios/5
